import React, { useState } from 'react';
import { useFarm } from '../context/FarmContext';
import { FileText, Printer, Download, MapPin, Wrench, Boxes, ClipboardList, Users, QrCode, CheckCircle2, AlertTriangle } from 'lucide-react';

export const ReportsManager: React.FC = () => {
  const { plots, resources, inventory, activities, workers, qrRecords } = useFarm();
  const [reportType, setReportType] = useState<string>('executive');

  const lowStockList = inventory.filter(i => i.status === 'Low Stock' || i.status === 'Out of Stock');
  const completedActivities = activities.filter(a => a.status === 'Completed');
  const totalHectares = plots.reduce((acc, p) => acc + p.size, 0);

  const handlePrintReport = () => {
    window.print();
  };

  return (
    <div className="space-y-6">
      
      {/* Header Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-white p-5 rounded-2xl border border-slate-200 shadow-sm">
        <div>
          <div className="flex items-center gap-2">
            <FileText className="w-5 h-5 text-emerald-700" />
            <h1 className="text-xl font-bold text-slate-900">Farm Management Reports & Audits</h1>
          </div>
          <p className="text-xs text-slate-500 mt-0.5">
            Comprehensive statistical analysis, QR code audit index, and inventory reports for U and E Grace Foundation Farm
          </p>
        </div>

        <button
          onClick={handlePrintReport}
          className="bg-emerald-800 hover:bg-emerald-700 text-white font-bold text-xs sm:text-sm px-5 py-2.5 rounded-xl transition-all flex items-center gap-2 cursor-pointer shadow-md self-start sm:self-auto"
        >
          <Printer className="w-4 h-4 text-amber-300" />
          <span>Print Management Report</span>
        </button>
      </div>

      {/* Report Selector Tabs */}
      <div className="flex items-center gap-2 border-b border-slate-200 pb-2 overflow-x-auto text-xs sm:text-sm">
        {[
          { id: 'executive', label: 'Executive Overview' },
          { id: 'plots', label: 'Farm Plots Report' },
          { id: 'resources', label: 'Equipment & Asset Condition' },
          { id: 'inventory', label: 'Inventory & Low Stock' },
          { id: 'activities', label: 'Activity Audit Log' },
          { id: 'qr_index', label: 'QR Master Index' },
        ].map((tab) => (
          <button
            key={tab.id}
            onClick={() => setReportType(tab.id)}
            className={`px-4 py-2 font-semibold rounded-xl transition-colors cursor-pointer whitespace-nowrap ${
              reportType === tab.id
                ? 'bg-emerald-700 text-white shadow-xs'
                : 'bg-white text-slate-600 hover:text-slate-900 border border-slate-200'
            }`}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* PRINTABLE REPORT CONTAINER */}
      <div className="bg-white rounded-2xl border border-slate-200 p-6 sm:p-8 shadow-sm space-y-6 printable-report">
        
        {/* Printable Official Letterhead Header */}
        <div className="border-b-2 border-emerald-800 pb-4 flex items-center justify-between">
          <div>
            <p className="text-xs font-bold text-amber-700 uppercase tracking-widest">
              OFFICIAL FARM AUDIT REPORT
            </p>
            <h2 className="text-xl sm:text-2xl font-black text-emerald-950">
              U & E GRACE FOUNDATION FARM
            </h2>
            <p className="text-xs text-slate-600">
              Obio Ndot, Akwa Ibom State, Nigeria · QR-Code Based Information System
            </p>
          </div>

          <div className="text-right text-xs text-slate-500 font-mono">
            <p>Report Date: {new Date().toLocaleDateString('en-GB')}</p>
            <p>Generated By: Engr. Sunday Akpan</p>
            <p className="text-emerald-700 font-bold">Status: Verified MVP</p>
          </div>
        </div>

        {/* SECTION 1: EXECUTIVE OVERVIEW */}
        {(reportType === 'executive' || reportType === 'all') && (
          <div className="space-y-4">
            <h3 className="text-base font-bold text-slate-900 border-b border-slate-200 pb-2 flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-600" />
              <span>1. Executive Summary & Asset Count</span>
            </h3>

            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 text-xs">
              <div className="bg-slate-50 p-4 rounded-xl border border-slate-200">
                <p className="text-slate-500">Total Cultivated Area</p>
                <p className="text-xl font-extrabold text-slate-900 font-mono mt-1">{totalHectares.toFixed(1)} Hectares</p>
                <p className="text-[11px] text-emerald-700 mt-1">{plots.length} Registered Plots</p>
              </div>

              <div className="bg-slate-50 p-4 rounded-xl border border-slate-200">
                <p className="text-slate-500">Machinery & Tools</p>
                <p className="text-xl font-extrabold text-slate-900 font-mono mt-1">{resources.length} Units</p>
                <p className="text-[11px] text-amber-700 mt-1">Tracked via QR Tags</p>
              </div>

              <div className="bg-slate-50 p-4 rounded-xl border border-slate-200">
                <p className="text-slate-500">Inventory Stock Items</p>
                <p className="text-xl font-extrabold text-slate-900 font-mono mt-1">{inventory.length} Categories</p>
                <p className="text-[11px] text-red-600 mt-1">{lowStockList.length} Low Stock Alerts</p>
              </div>

              <div className="bg-slate-50 p-4 rounded-xl border border-slate-200">
                <p className="text-slate-500">Recorded Farm Operations</p>
                <p className="text-xl font-extrabold text-slate-900 font-mono mt-1">{activities.length} Activities</p>
                <p className="text-[11px] text-emerald-700 mt-1">{completedActivities.length} Completed</p>
              </div>
            </div>
          </div>
        )}

        {/* SECTION 2: FARM PLOTS SUMMARY */}
        {(reportType === 'executive' || reportType === 'plots') && (
          <div className="space-y-3 pt-2">
            <h3 className="text-base font-bold text-slate-900 border-b border-slate-200 pb-2 flex items-center gap-2">
              <MapPin className="w-4 h-4 text-emerald-600" />
              <span>2. Farm Plot & Crop Breakdown</span>
            </h3>

            <table className="w-full text-left text-xs border border-slate-200 rounded-xl overflow-hidden">
              <thead className="bg-slate-100 font-bold text-slate-700 border-b border-slate-200">
                <tr>
                  <th className="p-2.5">Plot Code</th>
                  <th className="p-2.5">Plot Name</th>
                  <th className="p-2.5">Crop Planted</th>
                  <th className="p-2.5">Size</th>
                  <th className="p-2.5">Planting Date</th>
                  <th className="p-2.5">Status</th>
                  <th className="p-2.5">QR Identifier</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {plots.map((p) => (
                  <tr key={p.id}>
                    <td className="p-2.5 font-mono font-bold text-slate-600">{p.plot_code}</td>
                    <td className="p-2.5 font-bold text-slate-900">{p.plot_name}</td>
                    <td className="p-2.5">{p.crop_type}</td>
                    <td className="p-2.5 font-mono">{p.size} {p.size_unit || 'ha'}</td>
                    <td className="p-2.5 font-mono">{p.planting_date}</td>
                    <td className="p-2.5">
                      <span className="bg-emerald-100 text-emerald-800 text-[10px] font-bold px-2 py-0.5 rounded">
                        {p.status}
                      </span>
                    </td>
                    <td className="p-2.5 font-mono text-emerald-700 font-bold">{p.qr_code}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {/* SECTION 3: INVENTORY & LOW STOCK */}
        {(reportType === 'executive' || reportType === 'inventory') && (
          <div className="space-y-3 pt-2">
            <h3 className="text-base font-bold text-slate-900 border-b border-slate-200 pb-2 flex items-center gap-2">
              <Boxes className="w-4 h-4 text-blue-600" />
              <span>3. Inventory & Low Stock Reorder Audit</span>
            </h3>

            <table className="w-full text-left text-xs border border-slate-200 rounded-xl overflow-hidden">
              <thead className="bg-slate-100 font-bold text-slate-700 border-b border-slate-200">
                <tr>
                  <th className="p-2.5">Code</th>
                  <th className="p-2.5">Item Name</th>
                  <th className="p-2.5">Category</th>
                  <th className="p-2.5 text-right">Available Qty</th>
                  <th className="p-2.5 text-right">Min Threshold</th>
                  <th className="p-2.5">Stock Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {inventory.map((item) => (
                  <tr key={item.id} className={item.status === 'Low Stock' ? 'bg-amber-50/60' : ''}>
                    <td className="p-2.5 font-mono font-bold text-slate-600">{item.item_code}</td>
                    <td className="p-2.5 font-bold text-slate-900">{item.item_name}</td>
                    <td className="p-2.5">{item.category}</td>
                    <td className="p-2.5 text-right font-mono font-bold">{item.quantity} {item.unit}</td>
                    <td className="p-2.5 text-right font-mono text-slate-500">{item.minimum_stock} {item.unit}</td>
                    <td className="p-2.5">
                      <span
                        className={`text-[10px] font-bold px-2 py-0.5 rounded ${
                          item.status === 'Available'
                            ? 'bg-emerald-100 text-emerald-800'
                            : 'bg-amber-200 text-amber-950 font-extrabold'
                        }`}
                      >
                        {item.status}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}

        {/* SECTION 4: QR MASTER INDEX */}
        {(reportType === 'qr_index' || reportType === 'executive') && (
          <div className="space-y-3 pt-2">
            <h3 className="text-base font-bold text-slate-900 border-b border-slate-200 pb-2 flex items-center gap-2">
              <QrCode className="w-4 h-4 text-emerald-700" />
              <span>4. Master QR Code Registry Index ({qrRecords.length} Active Records)</span>
            </h3>

            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 text-xs font-mono">
              {qrRecords.map((qr) => (
                <div key={qr.id} className="bg-slate-50 border border-slate-200 p-2 rounded-lg flex items-center justify-between">
                  <span className="font-bold text-emerald-900">{qr.qr_code}</span>
                  <span className="text-[10px] text-slate-500 capitalize">{qr.record_type.replace('_', ' ')}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Report Footer Signature Box */}
        <div className="border-t border-slate-200 pt-6 mt-8 flex flex-col sm:flex-row justify-between items-end gap-6 text-xs text-slate-600">
          <div>
            <p className="font-bold text-slate-900">U and E Grace Foundation Farm Administration</p>
            <p>Ikot Ekpene, Akwa Ibom State, Nigeria</p>
          </div>

          <div className="text-center">
            <div className="border-b border-slate-400 w-48 mb-1"></div>
            <p className="font-semibold text-slate-800">Engr. Sunday Akpan</p>
            <p className="text-[11px] text-slate-500">Chief Farm Administrator Signature</p>
          </div>
        </div>

      </div>

    </div>
  );
};
